apiVersion: v1
kind: Pod
metadata:
  name: trailbrake-judge-pod
  namespace: default
  labels:
    app: trailbrake-judge-app
spec:
  # serviceAccountName: trailbrake-service-account
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  containers:
  - image: asia-east1-docker.pkg.dev/driverapp-2022/trailbrake-judge/trailbrake-judge:latest
    name: trailbrake-judge-pod
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: trailbrake-judge-service
spec:
  type: 
  selector:
    app: trailbrake-judge-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP